# Setup
title:        Nordlys
tagline:      A toolkit for entity-oriented and semantic search

baseurl:      ""
paginate:     1

# About/contact
author:
  name:       IAI group
  url:        http://iai.group

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman